/**
 * This file is auto-generated by the SatiDB types generator.
 * Do not edit this file manually.
 */

import type { Buffer } from 'buffer';

// --- GENERIC & QUERY TYPES ---

/** Describes the standard methods attached to every SatiDB entity instance. */
export type AugmentedMethods<T, D> = {
  /**
   * Updates the current entity with new data.
   * @param data A partial object of the entity's data to update.
   * @returns The updated entity, or null if the update fails.
   */
  update: (data: Partial<D>) => T | null;
  /** Deletes the current entity from the database. */
  delete: () => void;
};

/** Operators for filtering on fields like numbers, strings, or dates. */
export type FilterOperators<T> = {
  /** Greater than */
  $gt?: T;
  /** Greater than or equal to */
  $gte?: T;
  /** Less than */
  $lt?: T;
  /** Less than or equal to */
  $lte?: T;
  /** Not equal to */
  $ne?: T;
  /** Value is in the given array */
  $in?: T[];
};

/**
 * Defines the query conditions for an entity.
 * Allows direct value matching (e.g., { name: 'John' }) or operator-based filtering (e.g., { age: { $gt: 30 } }).
 */
export type QueryConditions<D> = {
  [P in keyof D]?: D[P] | FilterOperators<D[P]>;
};

/** Options for controlling find queries, such as sorting, pagination, and including related data. */
export type FindOptions = {
    /** The maximum number of records to return. */
    $limit?: number;
    /** The number of records to skip for pagination. */
    $offset?: number;
    /** The field to sort by, with an optional direction. Example: 'createdAt:desc' */
    $sortBy?: string;
    /** A related entity or list of entities to eagerly load with the query. */
    $include?: string | string[];
};

/** The complete set of conditions for a find query, combining field filters and query options. */
export type FindQuery<D> = QueryConditions<D> & FindOptions;

/** Describes the accessor object for a one-to-many relationship (e.g., author.posts). */
export type OneToManyAccessor<T, D> = {
  /** Inserts a new related entity. */
  insert: (data: D) => T;
  /** Retrieves a single related entity matching the query. Returns null if not found. */
  get: (conditions: number | QueryConditions<D>) => T | null;
  /** An alias for get. Retrieves a single related entity matching the query. */
  findOne: (conditions: QueryConditions<D>) => T | null;
  /** Finds all related entities matching the query. */
  find: (query?: FindQuery<D>) => T[];
  /** Updates a related entity by its ID. */
  update: (id: number, data: Partial<D>) => T | null;
  /** Updates a related entity if it exists (based on query conditions), otherwise inserts a new one. */
  upsert: (conditions: QueryConditions<D>, data: Partial<D>) => T;
  /** Deletes a related entity by its ID, or all related entities if no ID is provided. */
  delete: (id?: number) => void;
  /** An alias for insert. */
  push: (data: D) => T;
};

/** Describes a top-level accessor on the DB object (e.g., db.authors). */
export type EntityAccessor<T, D> = {
    /** Inserts a new entity. */
    insert: (data: D) => T;
    /** Finds multiple entities using Prisma-like interface with where, orderBy, take. */
    findMany: (options: { where?: QueryConditions<D>; orderBy?: Record<keyof D, 'asc' | 'desc'>; take?: number }) => T[];
    /** Finds a unique entity using Prisma-like interface with where clause. */
    findUnique: (options: { where: QueryConditions<D> }) => T | null;
    /** Retrieves a single entity by its ID or by a set of query conditions. */
    get: (conditions: number | QueryConditions<D>) => T | null;
    /** An alias for get. Retrieves a single entity matching the query. */
    findOne: (conditions: QueryConditions<D>) => T | null;
    /** Finds all entities matching the query. */
    find: (query?: FindQuery<D>) => T[];
    /** Updates an entity by its ID. */
    update: (id: number, data: Partial<D>) => T | null;
    /** Updates an entity if it exists (based on query conditions), otherwise inserts a new one. */
    upsert: (conditions: QueryConditions<D>, data: Partial<D>) => T;
    /** Deletes an entity by its ID. */
    delete: (id: number) => void;
    /** Subscribes to database events ('insert', 'update', 'delete') for this entity type. */
    subscribe: (event: 'insert' | 'update' | 'delete', callback: (data: T) => void) => void;
    /** Unsubscribes from database events ('insert', 'update', 'delete') for this entity type. */
    unsubscribe: (event: 'insert' | 'update' | 'delete', callback: (data: T) => void) => void;
};

// --- DATA TYPES FOR CREATION ---
/** Data required to create a new `Process`. */
export type ProcessData = {
  id?: number;
  pid: number;
  workdir: string;
  command: string;
  name: string;
  env: string;
  configPath?: string;
  stdout_path: string;
  stderr_path: string;
  timestamp?: Date;
};

// --- AUGMENTED ENTITY TYPES ---
/** Represents a `Process` record from the database, including methods and relationship accessors. */
export type AugmentedProcess = {
  id: number;
  id?: number;
  pid: number;
  workdir: string;
  command: string;
  name: string;
  env: string;
  configPath?: string;
  stdout_path: string;
  stderr_path: string;
  timestamp: Date;
} & AugmentedMethods<AugmentedProcess, ProcessData>;

// --- DATABASE CLIENT TYPE ---

/** The base SatiDB client, providing transaction support. */
export type SatiDBClient = {
  /**
   * Wraps a series of database operations in a transaction.
   * If the callback function throws an error, the transaction is rolled back.
   * Otherwise, the transaction is committed.
   * @param callback The function to execute within the transaction.
   * @returns The result of the callback function.
   */
  transaction<T>(callback: () => T): T;
};

/** The fully-typed DB client, combining the base client with all entity accessors. */
export type DB = SatiDBClient & {
  /** Accessor for all `Process` entity operations. */
  process: EntityAccessor<AugmentedProcess, ProcessData>;
};
